MyYTLoader.Web/Models/ErrorViewModel.cs
namespace MyYTLoader.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyYTLoader.Web/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;
using MyYTLoader.DAL.Entities;
using MyYTLoader.DAL.Repositories;
using MyYTLoader.Domain;
using MyYTLoader.Domain.Services;

namespace MyYTLoader.Web.Controllers
{
    public class DownloadController: Controller
    {
        private readonly ILogsProvider _logsProvider;
        private readonly IDownloadService _downloadService;
        private readonly IRequestService requestService;

        public DownloadController(ILogsProvider logsProvider, 
            IDownloadService downloadService, 
            IVideoRepository videoRepository, 
            IRequestService requestService)
        {
            this._logsProvider = logsProvider;
            this._downloadService = downloadService;
            this.requestService = requestService;
        }

        // GET метод для отображения страницы
        public IActionResult Request(string video)
        {
            ViewData["Message"] = video;
            ViewBag.Test = video;
            
            return View("Request", requestService.GetAll());
        }
        
        // POST метод для обработки данных из формы
        [HttpPost]
        public IActionResult HandlePost(string name)
        {
            _logsProvider.AddLog(name);
            //_downloadService.Download(name);
            var videoGuid = requestService.AddVideo(name);
            // Логика обработки данных из формы
            // Например, сохраняем данные или выполняем валидацию

            /*if (string.IsNullOrEmpty(name))
            {
                // Если данные не заполнены, можно вернуть ошибку или запросить повторный ввод
                ModelState.AddModelError("", "Name and email are required.");
                return View("MyForm");  // Вернемся к форме с ошибкой
            }*/

            // Если все в порядке, можно отправить подтверждение или redirect

            return View("Request", requestService.GetAll());
        }
    }
}

MyYTLoader.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyYTLoader.Domain;
using MyYTLoader.Web.Models;
using System.Diagnostics;

namespace MyYTLoader.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ILogsProvider _logsProvider;

        public HomeController(ILogger<HomeController> logger, ILogsProvider logsProvider)
        {
            _logger = logger;
            _logsProvider = logsProvider;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewBag.Logs = _logsProvider.GetLogs();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyYTLoader.Web/Views/Download/Request.cshtml
@using MyYTLoader.DAL.Entities
@model List<VideoEntity>
@{
    ViewData["Title"] = "Страница запроса";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<h2>Ссылка на видео в YouTube</h2>

<form method="post" asp-action="HandlePost" asp-controller="Download">
    <div>
        <label for="name">Адрес:</label>
        <input type="text" id="name" name="name" />
    </div>
    <button type="submit">Скачать</button>
</form>

@if (@Model is not null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Адрес</th>
                <th scope="col">Дата</th>
                <th scope="col">Состояние</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">@(i+1)</th>
                    <td>@Model[i].Url</td>
                    <td>@Model[i].Created</td>
                    <td>@{
                            switch (Model[i].State){
                                case VideoState.New:
                                    <div class="badge badge-primary">Новое</div>
                                    break;
                                case VideoState.Processing:
                                    <div class="badge badge-warning">Скачиваю</div>
                                    break;
                                case VideoState.Done:
                                    <div class="badge badge-success">Готово</div>
                                    break;
                                case VideoState.Error:
                                    <div class="badge badge-danger">Ошибка</div>
                                    break;
                                case VideoState.Deleted:
                                    <div class="badge badge-secondary">Удалено</div>
                                    break;
                            }
                        }</td>
                </tr>
            }
        </tbody>
    </table>
}

MyYTLoader.Web/Views/Home/About.cshtml
<ul>
    @foreach (var item in ViewBag.Logs as IReadOnlyList<string>)
    {
        <li>@item</li>
    }
</ul>

MyYTLoader.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyYTLoader.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyYTLoader.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyYTLoader.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyYTLoader.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Download" asp-action="Request">Request</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MyYTLoader.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>